name: simple
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

flutter_intl:
  enabled: true

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.1

  provider: ^6.0.3
  flutter_bloc: ^8.0.1

  dio: ^4.0.6
  retrofit: ^3.0.1+1
  dartz: ^0.10.1
  injectable: ^1.5.3
  get_it: ^7.2.0
  freezed_annotation: ^2.1.0

  flutter_svg: ^1.0.3
  shimmer: ^2.0.0
  image_cropper: ^2.0.3
  image_picker: ^0.8.5+3
  cached_network_image: ^3.2.1

  url_launcher: ^6.1.5

  annotations:
    git:
      url: https://github.com/amirsheibani/modelGeneratorsAnnotation.git
      ref: main # branch name
      version: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  test: ^1.17.12
  mocktail: ^0.3.0
  bloc_test: ^9.1.0
  flutter_lints: ^2.0.0
  freezed: ^2.1.0+1
  build_runner: ^2.2.0
  injectable_generator: ^1.5.3
  retrofit_generator: ^4.0.1
  json_serializable: ^6.2.0
  generators:
    git:
      url: https://github.com/amirsheibani/modelGenerator.git
      ref: main # branch name
      version: any

flutter:
  uses-material-design: true

